# Generated by Django 2.0.1 on 2018-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20180516_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
