# Generated by Django 2.0.1 on 2018-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20180519_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhouses',
            old_name='type_of_room',
            new_name='type_of_apartment',
        ),
        migrations.AddField(
            model_name='myhouses',
            name='Number_of_rooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_rent',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
    ]
