# Generated by Django 2.0.1 on 2018-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20180610_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
