# Generated by Django 2.0.1 on 2018-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20180611_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='name_of_accomodation',
            field=models.CharField(max_length=20),
        ),
    ]
