# Generated by Django 2.0.1 on 2018-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='image2',
            field=models.ImageField(default='s', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='image3',
            field=models.ImageField(default='s', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
