# Generated by Django 2.0.1 on 2018-06-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20180611_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='myhouses',
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(default='ss', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(default='ss', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
