# Generated by Django 2.0.1 on 2018-06-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20180611_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='11', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='myhouses',
            field=models.ForeignKey(default='11', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='houses.Myhouses'),
            preserve_default=False,
        ),
    ]
