# Generated by Django 2.0.1 on 2018-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_auto_20180612_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhouses',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='myhouses',
            name='image3',
        ),
    ]
