# Generated by Django 2.0.1 on 2018-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20180612_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='myhouses',
            old_name='image',
            new_name='house_image',
        ),
    ]
