# Generated by Django 2.0.1 on 2018-06-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_auto_20180612_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='myhouses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='houses.Myhouses'),
        ),
    ]
