# Generated by Django 2.0.1 on 2018-06-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0017_auto_20180613_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='myhouses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='houses.Myhouses'),
        ),
    ]
