# Generated by Django 2.0.1 on 2018-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0018_auto_20180613_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='house_image2',
            field=models.ImageField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
