# Generated by Django 2.0.1 on 2018-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_myhouses_house_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='house_image3',
            field=models.ImageField(default=22, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image4',
            field=models.ImageField(default=22, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image5',
            field=models.ImageField(default=44, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image6',
            field=models.ImageField(default=33, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
