# Generated by Django 2.0.1 on 2018-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_auto_20180613_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhouses',
            name='house_image10',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image11',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image12',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image7',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image8',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myhouses',
            name='house_image9',
            field=models.ImageField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
