# Generated by Django 2.0.1 on 2018-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_auto_20180616_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='house_image10',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image11',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image12',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image7',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image8',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='myhouses',
            name='house_image9',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
