# Generated by Django 2.0.1 on 2018-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20180616_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouses',
            name='type_of_apartment',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Self Contain', 'Self_contained'), ('Bungalow', 'Bungalow'), ('Mini Flat', 'Mini_flat'), ('Duplex', 'Duplex')], max_length=2),
        ),
    ]
