# Generated by Django 2.0.1 on 2018-06-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_auto_20180617_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='myhouses',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
